import turtle
Rafael = turtle.Turtle()
Rafael.color("purple")
Rafael.pensize(4)
Rafael.forward(90)
Rafael.left(90)
Rafael.forward(90)
Rafael.left(90)
Rafael.forward(90)
Rafael.left(90)
Rafael.forward(90)

Rafael.color("white")
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(90)
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(90)
Rafael.right(90)

Rafael.color("green")
Rafael.left(-45)
Rafael.forward(-65)
Rafael.left(-90)
Rafael.forward(0)
Rafael.forward(-65)

Rafael.color("blue")
Rafael.forward(35)
Rafael.right(50)
Rafael.forward(30)
Rafael.forward(90)

Rafael.color("yellow")
Rafael.right(0)
Rafael.circle(100, steps=10)
